#!/usr/bin/env bash
# Cron: 02:00 daily — reset token budgets + generate yesterday usage report
set -euo pipefail

source /root/brain/.env.api-keys 2>/dev/null || true
SUPA_URL="${SUPABASE_URL:-https://dlbnjiomldlijbshxysh.supabase.co}"
SUPA_KEY="${SUPABASE_SERVICE_ROLE_KEY:-${SUPABASE_ACCESS_TOKEN:-}}"

YESTERDAY=$(date -d 'yesterday' +%Y-%m-%d)
REPORT_DIR="/root/brain/memory/tokens"
mkdir -p "$REPORT_DIR"
REPORT="$REPORT_DIR/$YESTERDAY.md"

# Snapshot before reset
SNAP=$(curl -sS "$SUPA_URL/rest/v1/brain_token_budget?select=agent_name,used_today,daily_budget&order=used_today.desc" \
  -H "apikey: $SUPA_KEY" -H "Authorization: Bearer $SUPA_KEY")

# Generate report
{
  echo "# Token Usage Report — $YESTERDAY"
  echo
  echo "_Generated by brain v2.1 cron at $(date -Iseconds)_"
  echo
  echo "| Agent | Used | Budget | % |"
  echo "|-------|-----:|-------:|--:|"
  TOKEN_SNAP="$SNAP" python3 -c "
import os, json
rows = json.loads(os.environ['TOKEN_SNAP'])
for r in rows:
    pct = r['used_today'] * 100 / max(r['daily_budget'], 1)
    print(f'| {r[\"agent_name\"]} | {r[\"used_today\"]} | {r[\"daily_budget\"]} | {pct:.1f}% |')
"
} > "$REPORT"

# Reset
RESET_COUNT=$(curl -sS -X POST "$SUPA_URL/rest/v1/rpc/brain_reset_token_budgets" \
  -H "apikey: $SUPA_KEY" -H "Authorization: Bearer $SUPA_KEY" \
  -H "Content-Type: application/json" -d '{}')

echo "[$(date -Iseconds)] Token budgets reset: $RESET_COUNT agents. Report: $REPORT"
